name: rpl_tag_engine_module
services:
  rpl_tag_engine_module:
    container_name: rpl_tag_engine_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    command: python -m rpl_tag_engine_rest_node --port 3097  --host ${HOST} --database ${DATABASE} --camera ${CAMERA} --verbose ${VERBOSE}
    env_file: .env
    volumes:
      - ./src:/home/app/rpl_tag_engine_module/src
      - ./tests:/home/app/rpl_tag_engine_module/tests
    ports:
      - 3097:3097
